# Generated by Django 5.1.5 on 2025-02-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_alter_leaderboard_game_alter_leaderboard_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='school',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
